"""Generate the reference pages of the docs site from their sources (B09 §1.3, §9).

Nothing on these pages is typed by hand: the configuration reference comes from the pydantic
settings and ``configs/config.yaml``, the risk-level and compare pages from their YAML files,
the ADR index from the two decision logs and the command list from the poe tasks.

uv run poe docs-gen            # rewrite the pages
uv run poe docs-gen -- --check # exit 1 if a committed page is stale
"""

from __future__ import annotations

import re
import sys
import tomllib
from collections.abc import Callable
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel

from finsight.core.config import ENV_KEYS, REQUIRED_ENV, Settings

ROOT = Path(__file__).resolve().parents[1]
HEADER = "<!-- Generated by scripts/docs_gen.py from {source}. Do not edit by hand. -->\n\n"
SKIP_FIELDS = {"profile", "root"}


def _yaml(name: str) -> dict[str, Any]:
    data: dict[str, Any] = yaml.safe_load((ROOT / "configs" / name).read_text(encoding="utf-8"))
    return data


def _esc(text: str) -> str:
    return text.replace("|", "\\|")


def _cell(value: object) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, Path):
        value = value.as_posix()
    text = str(value) if not isinstance(value, str) else value
    return "`" + text.replace("|", "\\|") + "`" if text != "" else '`""`'


def _type(annotation: object) -> str:
    text = getattr(annotation, "__name__", None) or str(annotation)
    text = text.replace("typing.", "").replace("pathlib.", "")
    return text.replace("|", "\\|")


def _settings_rows(model: type[BaseModel], prefix: str = "") -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for name, field in model.model_fields.items():
        if not prefix and name in SKIP_FIELDS:
            continue
        key = f"{prefix}{name}"
        annotation = field.annotation
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            rows.extend(_settings_rows(annotation, f"{key}."))
            continue
        default = field.get_default(call_default_factory=True)
        env = "FINSIGHT_" + key.upper().replace(".", "__")
        if key == "demo_mode":
            env = "DEMO_MODE"
        rows.append((key, _type(annotation), _cell(default), f"`{env}`"))
    return rows


def _flatten(values: dict[str, Any], prefix: str = "") -> dict[str, Any]:
    flat: dict[str, Any] = {}
    for key, value in values.items():
        if isinstance(value, dict):
            flat.update(_flatten(value, f"{prefix}{key}."))
        else:
            flat[f"{prefix}{key}"] = value
    return flat


def config_page() -> str:
    """Every setting with its type, default and env var, then what each profile changes."""
    lines = [
        HEADER.format(source="finsight.core.config and configs/config.yaml"),
        "# Configuration and environment variables\n\n",
        "Settings load from `configs/config.yaml` for one profile (`FINSIGHT_PROFILE`, default "
        "`dev_light`). Environment variables win over the YAML; nested keys use `__`, so "
        "`llm.model` is `FINSIGHT_LLM__MODEL`. `UPLOADS_ENABLED=false` is the upload kill "
        "switch.\n\n",
        "## Settings\n\n",
        "| Key | Type | Default | Environment variable |\n| --- | --- | --- | --- |\n",
    ]
    lines += [f"| `{k}` | {t} | {d} | {e} |\n" for k, t, d, e in _settings_rows(Settings)]

    raw = _yaml("config.yaml")
    lines.append("\n## Profiles\n\nValues each profile sets (everything else keeps the default).\n")
    shared = _flatten({k: raw[k] for k in ("uploads",) if k in raw})
    if shared:
        lines.append("\n### Every profile\n\n| Key | Value |\n| --- | --- |\n")
        lines += [f"| `{k}` | {_cell(v)} |\n" for k, v in shared.items()]
    for name, values in raw.get("profiles", {}).items():
        lines.append(f"\n### `{name}`\n\n| Key | Value |\n| --- | --- |\n")
        lines += [f"| `{k}` | {_cell(v)} |\n" for k, v in _flatten(values or {}).items()]

    lines.append(
        "\n## Environment variables a deployment may set\n\nNames only: values never live "
        "in the repository (`.env.example` lists the same names).\n\n"
        "| Name | Required by |\n| --- | --- |\n"
    )
    for key in ENV_KEYS:
        needed = [p for p, names in REQUIRED_ENV.items() if key in names]
        lines.append(f"| `{key}` | {', '.join(f'`{p}`' for p in needed) or '—'} |\n")
    return "".join(lines)


def _provisional_note(cfg: dict[str, Any], what: str) -> str:
    if cfg.get("provisional"):
        return (
            f'!!! warning "Provisional"\n    The {what} below are placeholders made up for '
            "development, not measured. A local run over 2018–2023 IPOs replaces them.\n\n"
        )
    return f"Computed on {cfg.get('computed_on')} over {cfg.get('corpus_n')} past IPOs.\n\n"


def risklevel_page() -> str:
    """The risk-level points, thresholds and reference quantiles from ``risklevel.yaml``."""
    cfg = _yaml("risklevel.yaml")
    points = cfg["points"]
    q = cfg["reference_quantiles"]
    lines = [
        HEADER.format(source="configs/risklevel.yaml"),
        "# Risk level\n\n",
        "How the low / medium / high level is worked out (B02 §7.4). The level always "
        "carries its disclaimer; it is not a rating or advice.\n\n",
        _provisional_note(cfg, "thresholds and reference scores"),
        "## Points\n\n| Source | Points |\n| --- | --- |\n",
        f"| Red flag marked concern | {points['concern']} |\n",
        f"| Red flag marked watch | {points['watch']} |\n",
        f"| Rare serious risk (high seriousness, novelty below {cfg['unusual_below']}) "
        f"| {points['risk']} each, at most {points['max_risk_points']} |\n",
        "\nThe score is the points divided by the most points the checks that could run "
        "were able to give, so a missing check never looks like a clean record.\n\n",
        "## Thresholds\n\n| Level | Score |\n| --- | --- |\n",
        f"| Low | below {cfg['thresholds']['low_below']} |\n",
        f"| Medium | {cfg['thresholds']['low_below']} to below {cfg['thresholds']['high_from']} |\n",
        f"| High | {cfg['thresholds']['high_from']} and above |\n",
        "\n## Reference scores\n\n| Percentile | Score |\n| --- | --- |\n",
    ]
    lines += [f"| {i * 10} | {v} |\n" for i, v in enumerate(q)]
    lines.append(f"\nShown behind a click: `{str(cfg.get('behind_click', False)).lower()}`.\n")
    return "".join(lines)


def compare_page() -> str:
    """The past-IPO reference quantiles from ``compare.yaml``."""
    cfg = _yaml("compare.yaml")
    quantiles: dict[str, list[float]] = cfg["reference_quantiles"]
    metrics = list(quantiles)
    lines = [
        HEADER.format(source="configs/compare.yaml"),
        "# Compare: past-IPO reference\n\n",
        'The Compare tab places four numbers among past IPOs ("Higher than p% of past IPOs"). '
        "This is a fact about the distribution, not a judgement.\n\n",
        _provisional_note(cfg, "reference values"),
        "| Percentile | " + " | ".join(f"`{m}`" for m in metrics) + " |\n",
        "| --- |" + " --- |" * len(metrics) + "\n",
    ]
    for i in range(len(quantiles[metrics[0]])):
        lines.append(
            f"| {i * 10} | " + " | ".join(f"{quantiles[m][i]:g}" for m in metrics) + " |\n"
        )
    return "".join(lines)


ADR_HEADING = re.compile(r"^### ((?:B-)?ADR-\d+[a-z]?) (.+?)(?: — (.+))?$")


def adr_page() -> str:
    """One table row per decision in the Phase 1 and Phase 2 logs."""
    lines = [
        HEADER.format(source="docs/09_DECISIONS.md and docs/phase2/B08_DECISIONS.md"),
        "# Design decisions (ADR index)\n\n",
    ]
    for title, rel, link in (
        ("Phase 1", "docs/09_DECISIONS.md", "../09_DECISIONS.md"),
        ("Phase 2", "docs/phase2/B08_DECISIONS.md", "../phase2/B08_DECISIONS.md"),
    ):
        lines.append(f"## {title}\n\nFull text: [{Path(rel).name}]({link}).\n\n")
        lines.append("| ID | Decision | Status |\n| --- | --- | --- |\n")
        for line in (ROOT / rel).read_text(encoding="utf-8").splitlines():
            m = ADR_HEADING.match(line)
            if m:
                adr, name, status = m.groups()
                lines.append(f"| {adr} | {_esc(name)} | {status or '—'} |\n")
        lines.append("\n")
    return "".join(lines).rstrip("\n") + "\n"


def cli_page() -> str:
    """The poe tasks from ``pyproject.toml`` and the main module commands."""
    tasks: dict[str, Any] = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))[
        "tool"
    ]["poe"]["tasks"]
    lines = [
        HEADER.format(source="pyproject.toml [tool.poe.tasks]"),
        "# Commands\n\n## poe tasks\n\nRun with `uv run poe <task>`.\n\n",
        "| Task | What it does |\n| --- | --- |\n",
    ]
    for name, task in tasks.items():
        help_text = task.get("help", "") if isinstance(task, dict) else ""
        lines.append(f"| `{name}` | {_esc(help_text)} |\n")
    lines.append(
        "\n## Module commands\n\n"
        "| Command | What it does |\n| --- | --- |\n"
        "| `uv run python -m finsight.pipeline build --ipo <id>` | Build one showcase IPO |\n"
        "| `uv run python -m finsight.pipeline inspect --ipo <id>` | Print a short view of a parsed document (≤ 40 lines) |\n"
        "| `uv run python -m finsight.jobs run <doc_id> <job_id>` | Run the upload pipeline |\n"
        "| `uv run python -m finsight.jobs simplify <doc_id>` | Rewrite the queued risks |\n"
        "| `uv run python -m finsight.jobs sweep` | Delete uploads past retention |\n"
    )
    return "".join(lines)


PAGES: dict[str, Callable[[], str]] = {
    "docs/reference/config.md": config_page,
    "docs/reference/risklevel.md": risklevel_page,
    "docs/reference/compare.md": compare_page,
    "docs/reference/cli.md": cli_page,
    "docs/adr/index.md": adr_page,
}


def stale() -> list[str]:
    """Pages whose committed text differs from what the generator writes."""
    out = []
    for rel, make in PAGES.items():
        path = ROOT / rel
        if not path.exists() or path.read_text(encoding="utf-8") != make():
            out.append(rel)
    return out


def main() -> int:
    if "--check" in sys.argv:
        bad = stale()
        for rel in bad:
            print(f"{rel} is stale: run `uv run poe docs-gen`", file=sys.stderr)
        return 1 if bad else 0
    for rel, make in PAGES.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(make(), encoding="utf-8", newline="\n")
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
