"""Generate the reference pages of the docs site from their sources (B09 §1.3, §9).

Nothing on these pages is typed by hand: the configuration reference comes from the pydantic
settings and ``configs/config.yaml``, the risk-level and compare pages from their YAML files,
the ADR index from the two decision logs, the command list from the poe tasks, the glossary
from ``configs/glossary*.yaml`` and the data formats from the pydantic schemas and ``data/gold``.

Hand-written pages that quote numbers (evaluation, model cards, datasheets) hold generated
blocks between ``<!-- generated:NAME start -->`` and ``<!-- generated:NAME end -->``; only
the text between the markers is rewritten, and every number in it comes from ``eval_results/``.

uv run poe docs-gen            # rewrite the pages
uv run poe docs-gen -- --check # exit 1 if a committed page is stale
"""

from __future__ import annotations

import csv
import glob
import json
import re
import sys
import tomllib
from collections import Counter
from collections.abc import Callable
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel

from finsight.core.config import ENV_KEYS, REQUIRED_ENV, Settings

ROOT = Path(__file__).resolve().parents[1]
EVAL = ROOT / "eval_results"
GOLD = ROOT / "data" / "gold"
HEADER = "<!-- Generated by scripts/docs_gen.py from {source}. Do not edit by hand. -->\n\n"
SKIP_FIELDS = {"profile", "root"}


def _yaml(name: str) -> dict[str, Any]:
    data: dict[str, Any] = yaml.safe_load((ROOT / "configs" / name).read_text(encoding="utf-8"))
    return data


def _esc(text: str) -> str:
    return text.replace("|", "\\|")


def _cell(value: object) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, Path):
        value = value.as_posix()
    text = str(value) if not isinstance(value, str) else value
    return "`" + text.replace("|", "\\|") + "`" if text != "" else '`""`'


def _type(annotation: object) -> str:
    text = getattr(annotation, "__name__", None) or str(annotation)
    text = text.replace("typing.", "").replace("pathlib.", "")
    return text.replace("|", "\\|")


def _settings_rows(model: type[BaseModel], prefix: str = "") -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for name, field in model.model_fields.items():
        if not prefix and name in SKIP_FIELDS:
            continue
        key = f"{prefix}{name}"
        annotation = field.annotation
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            rows.extend(_settings_rows(annotation, f"{key}."))
            continue
        default = field.get_default(call_default_factory=True)
        env = "FINSIGHT_" + key.upper().replace(".", "__")
        if key == "demo_mode":
            env = "DEMO_MODE"
        rows.append((key, _type(annotation), _cell(default), f"`{env}`"))
    return rows


def _flatten(values: dict[str, Any], prefix: str = "") -> dict[str, Any]:
    flat: dict[str, Any] = {}
    for key, value in values.items():
        if isinstance(value, dict):
            flat.update(_flatten(value, f"{prefix}{key}."))
        else:
            flat[f"{prefix}{key}"] = value
    return flat


def config_page() -> str:
    """Every setting with its type, default and env var, then what each profile changes."""
    lines = [
        HEADER.format(source="finsight.core.config and configs/config.yaml"),
        "# Configuration and environment variables\n\n",
        "Settings load from `configs/config.yaml` for one profile (`FINSIGHT_PROFILE`, default "
        "`dev_light`). Environment variables win over the YAML; nested keys use `__`, so "
        "`llm.model` is `FINSIGHT_LLM__MODEL`. `UPLOADS_ENABLED=false` is the upload kill "
        "switch.\n\n",
        "## Settings\n\n",
        "| Key | Type | Default | Environment variable |\n| --- | --- | --- | --- |\n",
    ]
    lines += [f"| `{k}` | {t} | {d} | {e} |\n" for k, t, d, e in _settings_rows(Settings)]

    raw = _yaml("config.yaml")
    lines.append("\n## Profiles\n\nValues each profile sets (everything else keeps the default).\n")
    shared = _flatten({k: raw[k] for k in ("uploads",) if k in raw})
    if shared:
        lines.append("\n### Every profile\n\n| Key | Value |\n| --- | --- |\n")
        lines += [f"| `{k}` | {_cell(v)} |\n" for k, v in shared.items()]
    for name, values in raw.get("profiles", {}).items():
        lines.append(f"\n### `{name}`\n\n| Key | Value |\n| --- | --- |\n")
        lines += [f"| `{k}` | {_cell(v)} |\n" for k, v in _flatten(values or {}).items()]

    lines.append(
        "\n## Environment variables a deployment may set\n\nNames only: values never live "
        "in the repository (`.env.example` lists the same names).\n\n"
        "| Name | Required by |\n| --- | --- |\n"
    )
    for key in ENV_KEYS:
        needed = [p for p, names in REQUIRED_ENV.items() if key in names]
        lines.append(f"| `{key}` | {', '.join(f'`{p}`' for p in needed) or '—'} |\n")
    return "".join(lines)


def _provisional_note(cfg: dict[str, Any], what: str) -> str:
    if cfg.get("provisional"):
        return (
            f'!!! warning "Provisional"\n    The {what} below are placeholders made up for '
            "development, not measured. A local run over 2018–2023 IPOs replaces them.\n\n"
        )
    return f"Computed on {cfg.get('computed_on')} over {cfg.get('corpus_n')} past IPOs.\n\n"


def risklevel_page() -> str:
    """The risk-level points, thresholds and reference quantiles from ``risklevel.yaml``."""
    cfg = _yaml("risklevel.yaml")
    points = cfg["points"]
    q = cfg["reference_quantiles"]
    lines = [
        HEADER.format(source="configs/risklevel.yaml"),
        "# Risk level\n\n",
        "How the low / medium / high level is worked out (B02 §7.4). The level always "
        "carries its disclaimer; it is not a rating or advice.\n\n",
        _provisional_note(cfg, "thresholds and reference scores"),
        "## Points\n\n| Source | Points |\n| --- | --- |\n",
        f"| Red flag marked concern | {points['concern']} |\n",
        f"| Red flag marked watch | {points['watch']} |\n",
        f"| Rare serious risk (high seriousness, novelty below {cfg['unusual_below']}) "
        f"| {points['risk']} each, at most {points['max_risk_points']} |\n",
        "\nThe score is the points divided by the most points the checks that could run "
        "were able to give, so a missing check never looks like a clean record.\n\n",
        "## Thresholds\n\n| Level | Score |\n| --- | --- |\n",
        f"| Low | below {cfg['thresholds']['low_below']} |\n",
        f"| Medium | {cfg['thresholds']['low_below']} to below {cfg['thresholds']['high_from']} |\n",
        f"| High | {cfg['thresholds']['high_from']} and above |\n",
        "\n## Reference scores\n\n| Percentile | Score |\n| --- | --- |\n",
    ]
    lines += [f"| {i * 10} | {v} |\n" for i, v in enumerate(q)]
    lines.append(f"\nShown behind a click: `{str(cfg.get('behind_click', False)).lower()}`.\n")
    return "".join(lines)


def compare_page() -> str:
    """The past-IPO reference quantiles from ``compare.yaml``."""
    cfg = _yaml("compare.yaml")
    quantiles: dict[str, list[float]] = cfg["reference_quantiles"]
    metrics = list(quantiles)
    lines = [
        HEADER.format(source="configs/compare.yaml"),
        "# Compare: past-IPO reference\n\n",
        'The Compare tab places four numbers among past IPOs ("Higher than p% of past IPOs"). '
        "This is a fact about the distribution, not a judgement.\n\n",
        _provisional_note(cfg, "reference values"),
        "| Percentile | " + " | ".join(f"`{m}`" for m in metrics) + " |\n",
        "| --- |" + " --- |" * len(metrics) + "\n",
    ]
    for i in range(len(quantiles[metrics[0]])):
        lines.append(
            f"| {i * 10} | " + " | ".join(f"{quantiles[m][i]:g}" for m in metrics) + " |\n"
        )
    return "".join(lines)


ADR_HEADING = re.compile(r"^### ((?:B-)?ADR-\d+[a-z]?) (.+?)(?: — (.+))?$")


def adr_page() -> str:
    """One table row per decision in the Phase 1 and Phase 2 logs."""
    lines = [
        HEADER.format(source="docs/09_DECISIONS.md and docs/phase2/B08_DECISIONS.md"),
        "# Design decisions (ADR index)\n\n",
    ]
    for title, rel, link in (
        ("Phase 1", "docs/09_DECISIONS.md", "../09_DECISIONS.md"),
        ("Phase 2", "docs/phase2/B08_DECISIONS.md", "../phase2/B08_DECISIONS.md"),
    ):
        lines.append(f"## {title}\n\nFull text: [{Path(rel).name}]({link}).\n\n")
        lines.append("| ID | Decision | Status |\n| --- | --- | --- |\n")
        for line in (ROOT / rel).read_text(encoding="utf-8").splitlines():
            m = ADR_HEADING.match(line)
            if m:
                adr, name, status = m.groups()
                lines.append(f"| {adr} | {_esc(name)} | {status or '—'} |\n")
        lines.append("\n")
    return "".join(lines).rstrip("\n") + "\n"


def cli_page() -> str:
    """The poe tasks from ``pyproject.toml`` and the main module commands."""
    tasks: dict[str, Any] = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))[
        "tool"
    ]["poe"]["tasks"]
    lines = [
        HEADER.format(source="pyproject.toml [tool.poe.tasks]"),
        "# Commands\n\n## poe tasks\n\nRun with `uv run poe <task>`.\n\n",
        "| Task | What it does |\n| --- | --- |\n",
    ]
    for name, task in tasks.items():
        help_text = task.get("help", "") if isinstance(task, dict) else ""
        lines.append(f"| `{name}` | {_esc(help_text)} |\n")
    lines.append(
        "\n## Module commands\n\n"
        "| Command | What it does |\n| --- | --- |\n"
        "| `uv run python -m finsight.pipeline build --ipo <id>` | Build one showcase IPO |\n"
        "| `uv run python -m finsight.pipeline inspect --ipo <id>` | Print a short view of a parsed document (≤ 40 lines) |\n"
        "| `uv run python -m finsight.jobs run <doc_id> <job_id>` | Run the upload pipeline |\n"
        "| `uv run python -m finsight.jobs simplify <doc_id>` | Rewrite the queued risks |\n"
        "| `uv run python -m finsight.jobs sweep` | Delete uploads past retention |\n"
    )
    return "".join(lines)


def glossary_page() -> str:
    """Finance terms (English and Hindi, as the app shows them) and the ML terms of the docs."""
    finance = _yaml("glossary.yaml")["terms"]
    ml = _yaml("glossary_ml.yaml")["terms"]
    lines = [
        HEADER.format(source="configs/glossary.yaml and configs/glossary_ml.yaml"),
        "# Glossary\n\n",
        "The finance terms are the ones the app explains (UI spec §14), with the Hindi the app "
        "shows. The ML terms explain words used on the evaluation and model pages.\n\n",
        "## Finance terms\n\n| Term | Meaning | हिंदी |\n| --- | --- | --- |\n",
    ]
    for t in finance:
        hi = f"**{t['title']['hi']}**: {t['body']['hi']}"
        lines.append(f"| {_esc(t['title']['en'])} | {_esc(t['body']['en'])} | {_esc(hi)} |\n")
    lines.append("\n## ML and evaluation terms\n\n| Term | Meaning |\n| --- | --- |\n")
    lines += [f"| {_esc(t['term'])} | {_esc(t['body'])} |\n" for t in ml]
    return "".join(lines)


def _schema_type(annotation: object) -> str:
    if isinstance(annotation, type):
        return annotation.__name__
    text = re.sub(r"\b(?:[a-z_][\w]*\.)+([A-Za-z_]\w*)", r"\1", str(annotation))
    text = re.sub(r"Annotated\[(.+?), FieldInfo\([^)]*\)\]", r"\1", text)
    return text.replace("|", "\\|")


def _schema_table(model: type[BaseModel]) -> str:
    model.model_rebuild(force=True)  # resolve forward references the same way in every process
    rows = ["| Field | Type | Default |\n| --- | --- | --- |\n"]
    for name, field in model.model_fields.items():
        default = (
            "required"
            if field.is_required()
            else _cell(field.get_default(call_default_factory=True))
        )
        rows.append(f"| `{name}` | `{_schema_type(field.annotation)}` | {default} |\n")
    return "".join(rows)


def _gold_rows() -> list[tuple[str, int, list[str]]]:
    out = []
    for path in sorted(GOLD.glob("*.jsonl")):
        rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]
        out.append((path.name, len(rows), list(rows[0]) if rows else []))
    for path in sorted(GOLD.glob("*.csv")):
        with path.open(encoding="utf-8-sig", newline="") as fh:
            reader = list(csv.reader(fh))
        out.append((path.name, max(len(reader) - 1, 0), reader[0] if reader else []))
    return out


def data_formats_page() -> str:
    """Fields of the stored stage outputs (from the pydantic schemas) and the gold files."""
    from finsight.core import schemas
    from finsight.reports import ReportOverview

    lines = [
        HEADER.format(source="finsight.core.schemas, finsight.reports and data/gold"),
        "# Data formats\n\n",
        "What the pipeline stores for each document (`docs/<doc_id>/` in storage) and what the "
        "API returns. Types are Python annotations; `Decimal` values travel as strings.\n\n",
    ]
    for title, model in (
        ("Document record (`DocRecord`)", schemas.DocRecord),
        ("Job (`Job`)", schemas.Job),
        ("Report overview (`ReportOverview`, `GET /api/docs/{doc_id}/report`)", ReportOverview),
        ("Red flag (`RedFlag`, inside `redflags.json`)", schemas.RedFlag),
        ("Red flags file (`RedFlags`)", schemas.RedFlags),
        ("Risk (`Risk`, one row of `risks.json`)", schemas.Risk),
        ("Risk level (`RiskLevel`, `risklevel.json`)", schemas.RiskLevel),
        ("Reason behind the level (`RiskLevelReason`)", schemas.RiskLevelReason),
        ("Compare (`Compare`, `compare.json`)", schemas.Compare),
        ("Peer row (`Peer`)", schemas.Peer),
        ("Fact sheet (`XRay`, Phase 1)", schemas.XRay),
        ("One fact (`FieldResult`)", schemas.FieldResult),
    ):
        lines.append(f"## {title}\n\n{_schema_table(model)}\n")
    lines.append(
        "## Gold and review files (`data/gold/`)\n\n"
        "Rows exclude the CSV header. Labels written with AI help carry `label_source`.\n\n"
        "| File | Rows | Columns |\n| --- | --- | --- |\n"
    )
    for name, n, cols in _gold_rows():
        lines.append(f"| `{name}` | {n} | {_esc(', '.join(f'`{c}`' for c in cols))} |\n")
    lines.append(
        "\n## Result files (`eval_results/`)\n\n"
        "Every experiment writes one JSON file with its `experiment` id, the `git_sha`, the "
        "numbers with their `n` and 95 % intervals, and `notes`. The "
        "[evaluation page](../evaluation.md) lists which files exist.\n"
    )
    return "".join(lines)


EXPERIMENT_ROW = re.compile(r"^\| (E\d+[a-z]?) \| (.+)$")
# Files planned under one name that were written under another (the plan tables keep the names).
RESULT_ALIASES = {
    "eval_results/ladder/rules.json": ["ladder_table.json"],
    "eval_results/ladder/qa_pretrained.json": ["ladder_table.json"],
    "qa_finetuned_seed*.json": ["extractor_metrics-*.json"],
    "eval_results/answers.json": ["e7.json"],
    "eval_results/ladder/bilstm_crf_seed*.json": ["bilstm_metrics-*.json"],
    "eval_results/guard.json": ["guard.json", "guard_clf.json", "guard_compare.json"],
}


def _found(planned: str) -> list[str]:
    names = RESULT_ALIASES.get(planned) or [planned.removeprefix("eval_results/")]
    hits: list[str] = []
    for name in names:
        hits += sorted(Path(p).relative_to(EVAL).as_posix() for p in glob.glob(str(EVAL / name)))
    return hits


def experiments() -> list[dict[str, Any]]:
    """Experiments E1–E24 from the Phase 1 and Phase 2 plan tables, with their result files."""
    out = []
    for rel in ("docs/05_DATA_AND_EVALUATION.md", "docs/phase2/B04_DATA_AND_EVALUATION.md"):
        for line in (ROOT / rel).read_text(encoding="utf-8").splitlines():
            m = EXPERIMENT_ROW.match(line)
            if not m:
                continue
            cells = [c.strip() for c in line.strip("|").split(" | ")]
            planned = re.findall(r"`([^`]+\.json[^`]*)`", cells[-1])
            found = sorted({f for p in planned for f in _found(p)})
            out.append({"id": cells[0], "question": cells[1], "planned": planned, "found": found})
    return out


def _registry_block() -> str:
    rows = ["| ID | Question | Result files |\n| --- | --- | --- |\n"]
    for e in experiments():
        status = ", ".join(f"`{f}`" for f in e["found"]) if e["found"] else "not run yet"
        rows.append(f"| {e['id']} | {_esc(e['question'])} | {status} |\n")
    return "".join(rows)


def _phase2_block() -> str:
    rows = ["| ID | Question | Result files |\n| --- | --- | --- |\n"]
    for e in experiments():
        number = int(re.sub(r"\D", "", e["id"]))
        if number >= 13 or e["id"] in ("E8r", "E7c"):
            status = ", ".join(f"`{f}`" for f in e["found"]) if e["found"] else "not run yet"
            rows.append(f"| {e['id']} | {_esc(e['question'])} | {status} |\n")
    return "".join(rows)


def _results_block() -> str:
    sys.path.insert(0, str(ROOT / "scripts"))
    from readme_results import render

    return render(EVAL).replace("|---|---|---|---|", "| --- | --- | --- | --- |") + "\n"


def _notes_block() -> str:
    rows = []
    for path in sorted(EVAL.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict) and isinstance(data.get("notes"), str):
            rows.append(f"- `{path.name}`: {data['notes']}\n")
    return "".join(rows)


def _load(name: str) -> dict[str, Any]:
    data: dict[str, Any] = json.loads((EVAL / name).read_text(encoding="utf-8"))
    return data


def _seeds(prefix: str) -> list[dict[str, Any]]:
    return [_load(Path(p).name) for p in sorted(glob.glob(str(EVAL / f"{prefix}-*.json")))]


def _ladder_block(rung: str) -> str:
    table = _load("ladder_table.json")
    rows = [
        f"Gold `{table['gold_version']}`, seeds {', '.join(map(str, table['seeds']))}, "
        "bootstrap over IPOs. NVM = normalised value match.\n\n",
        "| Rung | Split | Full NVM [95 % CI] | Body-only NVM [95 % CI] | n (full / body) |\n",
        "| --- | --- | --- | --- | --- |\n",
    ]
    for key, data in table["ladder"].items():
        for split in ("dev", "test"):
            full, body = data[split]["full"], data[split]["body_only"]
            name = f"**{data['label']}**" if key == rung else data["label"]
            rows.append(
                f"| {name} | {split} | {full['nvm']:.2f} {_ci(full['nvm_ci95'])} | "
                f"{body['nvm']:.2f} {_ci(body['nvm_ci95'])} | {full['n']} / {body['n']} |\n"
            )
    return "".join(rows)


def _ci(pair: list[float]) -> str:
    return f"[{pair[0]:.2f}, {pair[1]:.2f}]"


def _failures_block(rung: str) -> str:
    examples = _load("ladder_table.json")["examples_test"][rung]
    wrong = [
        (field, ex)
        for part in ("full", "body_only")
        for field, items in examples.get(part, {}).items()
        for ex in items
        if not ex["correct"]
    ][:3]
    rows = ["| IPO | Field | Read | Checked value |\n| --- | --- | --- | --- |\n"]
    for field, ex in wrong:
        where = f"`{ex['ipo_id']}`" + (f" p.{ex['page']}" if ex.get("page") else "")
        read = _short(ex["read"]) if ex.get("read") else "(nothing found)"
        rows.append(f"| {where} | `{field}` | {read} | {_short(ex['checked'])} |\n")
    return "".join(rows)


def _short(value: object, limit: int = 120) -> str:
    text = _esc(str(value))
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def _training_block(prefix: str, keys: tuple[str, ...]) -> str:
    runs = _seeds(prefix)
    rows = [
        "| Seed | " + " | ".join(keys) + " | Dev EM | Dev F1 | HasAns F1 | NoAns acc |\n",
        "| --- |" + " --- |" * (len(keys) + 4) + "\n",
    ]
    for r in runs:
        rows.append(
            f"| {r['seed']} | "
            + " | ".join(_fmt(r.get(k)) for k in keys)
            + f" | {r['EM']:.3f} | {r['F1']:.3f} | {r['HasAns_F1']:.3f} | {r['NoAns_acc']:.3f} |\n"
        )
    first = runs[0]
    rows.append(
        f"\nBase: `{first['model']}`. Training examples: {first['n_train']}; dev examples: "
        f"{first['n_dev']} ({first['n_answerable']} answerable). GPUs: {first['n_gpu']} "
        "(Kaggle). Dev scores are on weak labels, not gold.\n"
    )
    if "hyperparameters" in first:
        hp = ", ".join(f"{k} {v}" for k, v in first["hyperparameters"].items())
        rows.append(f"Hyperparameters: {hp}; {first['n_params']:,} parameters.\n")
    return "".join(rows)


def _fmt(value: object) -> str:
    if isinstance(value, float):
        return f"{value:g}"
    return "—" if value is None else str(value)


def _rate(r: dict[str, Any]) -> str:
    return f"{r['hits']}/{r['n']} {_ci(r['wilson_95'])}"


def _guard_block() -> str:
    clf = _load("guard_clf.json")
    cmp_ = _load("guard_compare.json")
    rows = [
        "| Seed | Best epoch | Val F1 | Test F1 | Test block rate | Test false-block rate |\n",
        "| --- | --- | --- | --- | --- | --- |\n",
    ]
    for seed, r in clf["seeds"].items():
        rows.append(
            f"| {seed} | {r['best_epoch']} | {r['val']['f1']:.2f} | {r['test']['f1']:.2f} | "
            f"{r['test']['block_rate']:.2f} | {r['test']['false_block_rate']:.2f} |\n"
        )
    rows.append(
        f"\nBase: `{clf['model']}`; {next(iter(clf['seeds'].values()))['n_train']} training "
        f"questions; best seed by validation F1: {clf['best_seed_by_val_f1']}.\n\n"
        f"Held-out test ({cmp_['n_test']} questions, threshold {cmp_['threshold']}):\n\n"
        "| Guard | Blocks advice | False blocks on fact questions |\n| --- | --- | --- |\n"
    )
    for name in ("keyword", "muril"):
        o = cmp_[name]["overall"]
        rows.append(f"| {name} | {_rate(o['block_rate'])} | {_rate(o['false_block_rate'])} |\n")
    return "".join(rows)


def _corpus_block() -> str:
    c = _load("corpus_stats.json")
    kinds = ", ".join(f"{k} {v}" for k, v in c["by_doc_kind"].items())
    skipped = ", ".join(f"{k} {v}" for k, v in c["skipped"].items())
    years = "| Year | " + " | ".join(c["by_close_year"]) + " |\n"
    years += "| --- |" + " --- |" * len(c["by_close_year"]) + "\n"
    years += "| IPOs | " + " | ".join(str(v) for v in c["by_close_year"].values()) + " |\n"
    return (
        f"- IPOs: {c['n_ipos']} ({kinds}); one text per IPO: {str(c['one_text_per_ipo']).lower()}\n"
        f"- Median length: {c['pages_p50']} pages\n"
        f"- Key sections found: {c['key_sections_found']}\n"
        f"- Skipped: {skipped}\n\n" + years
    )


def _weaklabel_block() -> str:
    w = _load("weaklabel_stats.json")
    a = _load("weaklabel_audit.json")
    rows = [
        f"Label version {w['label_version']}, split seed {w['split_seed']}. "
        f"Train: {w['train']['ipos']} IPOs, {w['train']['examples']} examples "
        f"({w['train']['positives']} with an answer). Dev: {w['dev']['ipos']} IPOs, "
        f"{w['dev']['examples']} examples ({w['dev']['positives']} with an answer).\n\n",
        "| Field | Seed found (IPOs) | Positives | Negatives |\n| --- | --- | --- | --- |\n",
    ]
    for field, f in w["per_field"].items():
        rows.append(
            f"| `{field}` | {w['seed_coverage'][field]} | {f['positives']} | {f['negatives']} |\n"
        )
    rows.append(
        f"\nAudit (E1, measured on labels {a['measured_on']}; current {a['current_label_version']}):"
        f" {a['correct']}/{a['n']} correct, precision {a['precision']:.2f} "
        f"{_ci(a['wilson_95'])}. Errors: "
        + ", ".join(f"{k.replace('_', ' ')} {v}" for k, v in a["labels"].items() if k != "correct")
        + f". Audit labels: `{', '.join(a['label_sources'])}`.\n"
    )
    return "".join(rows)


def _gold_block() -> str:
    rows = ["| File | Rows | IPOs | Label source |\n| --- | --- | --- | --- |\n"]
    for name in (
        "gold_values.jsonl",
        "questions_dev.jsonl",
        "questions_test.jsonl",
        "weaklabel_audit.jsonl",
        "gold_v3_template.jsonl",
    ):
        data = [json.loads(x) for x in (GOLD / name).read_text(encoding="utf-8").splitlines() if x]
        sources = Counter(str(d.get("label_source") or "none yet") for d in data)
        rows.append(
            f"| `{name}` | {len(data)} | {len({d['ipo_id'] for d in data})} | "
            + ", ".join(f"`{k}` {v}" for k, v in sources.items())
            + " |\n"
        )
    langs: Counter[str] = Counter()
    review: Counter[str] = Counter()
    for name in ("questions_dev.jsonl", "questions_test.jsonl"):
        for x in (GOLD / name).read_text(encoding="utf-8").splitlines():
            if x:
                row = json.loads(x)
                langs[row["language"]] += 1
                review[row["review_status"]] += 1
    with (GOLD / "advice_guard_set.csv").open(encoding="utf-8-sig", newline="") as fh:
        guard = list(csv.DictReader(fh))
    reviewed = sum(1 for g in guard if g["reviewed_by_akshat (Y/edit)"].strip())
    rows.append(
        "\nQuestions (dev + test) by language: "
        + ", ".join(f"{k} {v}" for k, v in sorted(langs.items()))
        + "; review status: "
        + ", ".join(f"{k} {v}" for k, v in sorted(review.items()))
        + f". Advice-guard set: {len(guard)} questions ("
        + ", ".join(f"{k} {v}" for k, v in sorted(Counter(g["language"] for g in guard).items()))
        + f"), {reviewed} reviewed by Akshat.\n"
    )
    return "".join(rows)


BLOCKS: dict[str, dict[str, Callable[[], str]]] = {
    "docs/evaluation.md": {
        "results": _results_block,
        "registry": _registry_block,
        "notes": _notes_block,
    },
    "docs/model_cards/extractor_qa.md": {
        "training": lambda: _training_block(
            "extractor_metrics",
            ("epochs", "learning_rate", "batch_size", "max_len", "train_runtime_s"),
        ),
        "ladder": lambda: _ladder_block("qa_finetuned"),
        "failures": lambda: _failures_block("qa_finetuned"),
    },
    "docs/model_cards/bilstm_crf.md": {
        "training": lambda: _training_block(
            "bilstm_metrics",
            ("epochs", "best_epoch", "learning_rate", "batch_size", "train_runtime_s"),
        ),
        "ladder": lambda: _ladder_block("bilstm_crf"),
        "failures": lambda: _failures_block("bilstm_crf"),
    },
    "docs/model_cards/guard_muril.md": {"results": _guard_block},
    "docs/datasheets/corpus.md": {"stats": _corpus_block},
    "docs/datasheets/weak_labels.md": {"stats": _weaklabel_block},
    "docs/datasheets/gold_sets.md": {"stats": _gold_block},
    "report/07_results.md": {"phase2": _phase2_block},
}


def _marker(name: str, end: bool = False) -> str:
    return f"<!-- generated:{name} {'end' if end else 'start'} -->"


def fill_blocks(text: str, blocks: dict[str, Callable[[], str]]) -> str:
    """Rewrite the text between each pair of ``generated:NAME`` markers.

    Raises:
        ValueError: when a page lacks the markers for one of its blocks.
    """
    for name, make in blocks.items():
        start, end = _marker(name), _marker(name, end=True)
        if start not in text or end not in text:
            raise ValueError(f"missing {start} / {end}")
        head, rest = text.split(start, 1)
        _, tail = rest.split(end, 1)
        text = f"{head}{start}\n\n{make().rstrip()}\n\n{end}{tail}"
    return text


PAGES: dict[str, Callable[[], str]] = {
    "docs/reference/config.md": config_page,
    "docs/reference/risklevel.md": risklevel_page,
    "docs/reference/compare.md": compare_page,
    "docs/reference/cli.md": cli_page,
    "docs/adr/index.md": adr_page,
    "docs/glossary.md": glossary_page,
    "docs/reference/data_formats.md": data_formats_page,
}


def stale() -> list[str]:
    """Pages whose committed text differs from what the generator writes."""
    out = []
    for rel, make in PAGES.items():
        path = ROOT / rel
        if not path.exists() or path.read_text(encoding="utf-8") != make():
            out.append(rel)
    for rel, blocks in BLOCKS.items():
        path = ROOT / rel
        current = path.read_text(encoding="utf-8")
        if fill_blocks(current, blocks) != current:
            out.append(rel)
    return out


def main() -> int:
    if "--check" in sys.argv:
        bad = stale()
        for rel in bad:
            print(f"{rel} is stale: run `uv run poe docs-gen`", file=sys.stderr)
        return 1 if bad else 0
    for rel, make in PAGES.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(make(), encoding="utf-8", newline="\n")
        print(f"wrote {rel}")
    for rel, blocks in BLOCKS.items():
        path = ROOT / rel
        path.write_text(
            fill_blocks(path.read_text(encoding="utf-8"), blocks), "utf-8", newline="\n"
        )
        print(f"filled {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
