/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ipos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ipos */
        get: operations["list_ipos_api_ipos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ipos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ipo */
        get: operations["get_ipo_api_ipos__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ipos/{id}/xray": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Xray */
        get: operations["get_xray_api_ipos__id__xray_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ipos/{id}/pages/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Image */
        get: operations["get_page_image_api_ipos__id__pages__n__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ipos/{id}/pages/{n}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Words */
        get: operations["get_page_words_api_ipos__id__pages__n__words_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ipos/{id}/suggested-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggested Questions */
        get: operations["suggested_questions_api_ipos__id__suggested_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice */
        post: operations["voice_api_voice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_api_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab Ladder */
        get: operations["lab_ladder_api_lab_ladder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab Fields */
        get: operations["lab_fields_api_lab_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/verifier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab Verifier */
        get: operations["lab_verifier_api_lab_verifier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/weaklabels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab Weaklabels */
        get: operations["lab_weaklabels_api_lab_weaklabels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/frontier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab Frontier */
        get: operations["lab_frontier_api_lab_frontier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab Retrieval */
        get: operations["lab_retrieval_api_lab_retrieval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/asr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab Asr */
        get: operations["lab_asr_api_lab_asr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary */
        get: operations["glossary_api_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiCandidate */
        ApiCandidate: {
            /** Extractor */
            extractor: string;
            /**
             * Doc
             * @enum {string}
             */
            doc: "rhp" | "prospectus";
            /** Raw */
            raw: string;
            /** Value */
            value?: (components["schemas"]["Money"] | components["schemas"]["Count"] | components["schemas"]["Percent"] | components["schemas"]["Placeholder"] | components["schemas"]["Range"] | components["schemas"]["TextValue"] | components["schemas"]["ListValue"] | components["schemas"]["TableValue"]) | null;
            /** Page */
            page: number;
            /** Score */
            score: number;
            /** Gold Match */
            gold_match?: boolean | null;
        };
        /**
         * BidClosedInfo
         * @description "Bid/offer closed on" as printed on the Prospectus cover (read by the extract stage).
         */
        BidClosedInfo: {
            /**
             * Closed On
             * Format: date
             */
            closed_on: string;
            /**
             * Doc
             * @default prospectus
             * @enum {string}
             */
            doc: "rhp" | "prospectus";
            /** Page */
            page: number;
        };
        /** Body_voice_api_voice_post */
        Body_voice_api_voice_post: {
            /**
             * Audio
             * @description webm/opus or wav, at most 20 s.
             */
            audio: string;
            /**
             * Language
             * @default hi
             */
            language: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Ipo Id */
            ipo_id: string;
            /** Question */
            question: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "hi";
            /**
             * Source
             * @default typed
             * @enum {string}
             */
            source: "typed" | "voice" | "chip";
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** CheckResult */
        CheckResult: {
            /** Check */
            check: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "unverifiable" | "contradicted";
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "verified" | "scale_mismatch" | "wrong_value" | "wrong_metric" | "not_found" | "placeholder" | "section_not_found" | "extractors_disagree" | "not_in_document";
            /** Reason */
            reason: string;
            /** Answer Value */
            answer_value?: (components["schemas"]["Money"] | components["schemas"]["Count"] | components["schemas"]["Percent"] | components["schemas"]["Placeholder"] | components["schemas"]["Range"]) | null;
            /** Evidence Value */
            evidence_value?: (components["schemas"]["Money"] | components["schemas"]["Count"] | components["schemas"]["Percent"] | components["schemas"]["Placeholder"] | components["schemas"]["Range"]) | null;
            /** Evidence Passage Id */
            evidence_passage_id?: string | null;
            /** Evidence Char Span */
            evidence_char_span?: [
                number,
                number
            ] | null;
        };
        /**
         * Companion
         * @description The same field read from the other document (RHP ``[●]`` beside the Prospectus value).
         */
        Companion: {
            /**
             * Doc
             * @enum {string}
             */
            doc: "rhp" | "prospectus";
            /** Page */
            page: number;
            /** Value */
            value?: (components["schemas"]["Money"] | components["schemas"]["Count"] | components["schemas"]["Percent"] | components["schemas"]["Placeholder"] | components["schemas"]["Range"] | components["schemas"]["TextValue"] | components["schemas"]["ListValue"] | components["schemas"]["TableValue"]) | null;
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | null;
        };
        /** Count */
        Count: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "count";
            /** Value */
            value: number;
            /** Raw */
            raw: string;
            /**
             * Unit
             * @default null
             */
            unit: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "ipo_not_found" | "not_available" | "page_out_of_range" | "llm_unavailable" | "models_warming_up" | "asr_failed" | "audio_too_long" | "rate_limited" | "validation_error" | "internal_error";
            /** Message */
            message: string;
            /** Hint */
            hint?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FieldCheck */
        FieldCheck: {
            /** Check */
            check: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "unverifiable" | "contradicted";
            /** Reason */
            reason: string;
        };
        /** GlossaryEntry */
        GlossaryEntry: {
            /** Term */
            term: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warming" | "degraded";
            /** Profile */
            profile: string;
            /** Demo Mode */
            demo_mode: boolean;
            /** Models */
            models: {
                [key: string]: components["schemas"]["ModelStatus"];
            };
            /** Version */
            version: string;
            /** Git Sha */
            git_sha?: string | null;
        };
        /** IpoDetail */
        IpoDetail: {
            /** Id */
            id: string;
            /** Company */
            company: string;
            /** Rhp Pages */
            rhp_pages: number;
            /** Prospectus Pages */
            prospectus_pages?: number | null;
            page_size: components["schemas"]["PageSize"];
            /** Sections */
            sections: components["schemas"]["SectionInfo"][];
        };
        /** IpoSummary */
        IpoSummary: {
            /** Id */
            id: string;
            /** Company */
            company: string;
            /** Sector */
            sector?: string | null;
            /** Listing Date */
            listing_date?: string | null;
            /** Rhp Pages */
            rhp_pages: number;
            /** Issue Size Inr */
            issue_size_inr?: string | null;
            /** Fresh Inr */
            fresh_inr?: string | null;
            /** Ofs Inr */
            ofs_inr?: string | null;
            /**
             * Xray Status
             * @enum {string}
             */
            xray_status: "ready" | "building" | "missing";
        };
        /** ListValue */
        ListValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "list";
            /** Items */
            items: string[];
        };
        /** ModelStatus */
        ModelStatus: {
            /** Name */
            name?: string | null;
            /** Loaded */
            loaded: boolean;
            /** Lazy */
            lazy?: boolean | null;
        };
        /** Money */
        Money: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "money";
            /** Value Inr */
            value_inr: string | null;
            /**
             * Currency
             * @enum {string}
             */
            currency: "INR" | "USD" | "OTHER";
            /** Raw */
            raw: string;
            /**
             * Scale Word
             * @default null
             */
            scale_word: string | null;
            /** Precision */
            precision: number;
        };
        /** PageSize */
        PageSize: {
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** PageWord */
        PageWord: {
            /** T */
            t: string;
            /** B */
            b: [
                number,
                number,
                number,
                number
            ];
        };
        /** PageWords */
        PageWords: {
            /** Page */
            page: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Words */
            words: components["schemas"]["PageWord"][];
        };
        /** Percent */
        Percent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "percent";
            /**
             * Value
             * @example 8000000000.00
             */
            value: string;
            /** Raw */
            raw: string;
            /**
             * Is Bps
             * @default false
             */
            is_bps: boolean;
        };
        /**
         * Placeholder
         * @description A blank the document fills in later: [●] or [•]. Never a zero.
         */
        Placeholder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "placeholder";
            /** Raw */
            raw: string;
        };
        /** Range */
        Range: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "range";
            low: components["schemas"]["Money"];
            high: components["schemas"]["Money"];
            /** Raw */
            raw: string;
        };
        /** SectionInfo */
        SectionInfo: {
            /** Id */
            id: string;
            /**
             * Doc
             * @enum {string}
             */
            doc: "rhp" | "prospectus";
            /** Title */
            title: string;
            /** Start Page */
            start_page: number;
            /** Printed Start Page */
            printed_start_page?: string | null;
            /** End Page */
            end_page: number;
        };
        /**
         * SourceSentence
         * @description The line of the page a value sits on; ``hit`` is the character span of the value in it.
         */
        SourceSentence: {
            /** Text */
            text: string;
            /** Hit */
            hit: [
                number,
                number
            ];
        };
        /** SuggestedQuestion */
        SuggestedQuestion: {
            /** Text */
            text: string;
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi";
            /**
             * Kind
             * @enum {string}
             */
            kind: "normal" | "trick" | "advice";
        };
        /** TableValue */
        TableValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "table";
            /** Columns */
            columns: string[];
            /** Rows */
            rows: string[][];
        };
        /** TextValue */
        TextValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Text */
            text: string;
        };
        /** Trace */
        Trace: {
            /** Trace Id */
            trace_id: string;
            /** Question */
            question: string;
            /** Stages */
            stages: {
                [key: string]: unknown;
            }[];
            /** Passages */
            passages: {
                [key: string]: unknown;
            }[];
            /** Prompt */
            prompt: string;
            /** Checks */
            checks: components["schemas"]["CheckResult"][];
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
        };
        /** VoiceResponse */
        VoiceResponse: {
            /** Transcript */
            transcript: string;
            /** Language */
            language: string;
            /** Asr Model */
            asr_model: string;
            /** Ms */
            ms: number;
        };
        /** XRayField */
        XRayField: {
            /** Field Id */
            field_id: string;
            /** Label En */
            label_en: string;
            /** Label Hi */
            label_hi: string;
            /** Type */
            type: string;
            /** Value */
            value?: (components["schemas"]["Money"] | components["schemas"]["Count"] | components["schemas"]["Percent"] | components["schemas"]["Placeholder"] | components["schemas"]["Range"] | components["schemas"]["TextValue"] | components["schemas"]["ListValue"] | components["schemas"]["TableValue"]) | null;
            /**
             * Doc
             * @enum {string}
             */
            doc: "rhp" | "prospectus";
            /** Page */
            page: number;
            /** Printed Page */
            printed_page?: string | null;
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | null;
            sentence?: components["schemas"]["SourceSentence"] | null;
            /** Extractor */
            extractor: string;
            /** Score */
            score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "verified" | "unverifiable" | "contradicted";
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "verified" | "scale_mismatch" | "wrong_value" | "wrong_metric" | "not_found" | "placeholder" | "section_not_found" | "extractors_disagree" | "not_in_document";
            /** Reason */
            reason: string;
            companion?: components["schemas"]["Companion"] | null;
            /** Checks */
            checks: components["schemas"]["FieldCheck"][];
            /** Candidates */
            candidates: components["schemas"]["ApiCandidate"][];
        };
        /** XRayResponse */
        XRayResponse: {
            /** Ipo Id */
            ipo_id: string;
            /** Company */
            company: string;
            /**
             * Built At
             * Format: date-time
             */
            built_at: string;
            /** Fields */
            fields: components["schemas"]["XRayField"][];
            /** Derived */
            derived: {
                [key: string]: string;
            };
            bid_closed?: components["schemas"]["BidClosedInfo"] | null;
        };
        /** StageEvent */
        StageEvent: {
            /**
             * Name
             * @enum {string}
             */
            name: "guard" | "retrieving" | "generating" | "verifying" | "done";
            /**
             * Status
             * @enum {string}
             */
            status: "start" | "end";
            /**
             * Ms
             * @default null
             */
            ms: number | null;
        };
        /**
         * FactSummary
         * @description A short X-Ray fact shown on the advice-refusal card.
         */
        FactSummary: {
            /** Field Id */
            field_id: string;
            /** Label En */
            label_en: string;
            /** Label Hi */
            label_hi: string;
            /** Display */
            display: string;
            /**
             * Doc
             * @enum {string}
             */
            doc: "rhp" | "prospectus";
            /** Page */
            page: number;
        };
        /** GuardEvent */
        GuardEvent: {
            /** Blocked */
            blocked: boolean;
            /** Reason */
            reason: string;
            /** Facts */
            facts: components["schemas"]["FactSummary"][];
        };
        /** RetrievedPassage */
        RetrievedPassage: {
            /** N */
            n: number;
            /** Id */
            id: string;
            /**
             * Doc
             * @enum {string}
             */
            doc: "rhp" | "prospectus";
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Section */
            section: string;
            /** Snippet */
            snippet: string;
            /**
             * Bm25 Rank
             * @default null
             */
            bm25_rank: number | null;
            /**
             * Dense Rank
             * @default null
             */
            dense_rank: number | null;
            /**
             * Fused Rank
             * @default null
             */
            fused_rank: number | null;
            /**
             * Rerank Score
             * @default null
             */
            rerank_score: number | null;
        };
        /** RetrievalEvent */
        RetrievalEvent: {
            /** Passages */
            passages: components["schemas"]["RetrievedPassage"][];
            /** Dropped */
            dropped: components["schemas"]["RetrievedPassage"][];
        };
        /** AbstainEvent */
        AbstainEvent: {
            /**
             * Reason
             * @constant
             */
            reason: "low_retrieval_score";
            /** @default null */
            closest_passage: components["schemas"]["RetrievedPassage"] | null;
        };
        /** TokenEvent */
        TokenEvent: {
            /** Text */
            text: string;
        };
        /** Citation */
        Citation: {
            /** N */
            n: number;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
        };
        /** AnswerEvent */
        AnswerEvent: {
            /** Text */
            text: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** Evidence */
        Evidence: {
            /** Passage Id */
            passage_id: string;
            /**
             * Doc
             * @enum {string}
             */
            doc: "rhp" | "prospectus";
            /** Page */
            page: number;
            /** Char Span */
            char_span: [
                number,
                number
            ];
            /**
             * Bbox
             * @default null
             */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Value
             * @default null
             */
            value: (components["schemas"]["Money"] | components["schemas"]["Count"] | components["schemas"]["Percent"] | components["schemas"]["Placeholder"] | components["schemas"]["Range"]) | null;
        };
        /** VerdictEvent */
        VerdictEvent: {
            /** Index */
            index: number;
            /** Answer Char Span */
            answer_char_span: [
                number,
                number
            ];
            /** Answer Value */
            answer_value: components["schemas"]["Money"] | components["schemas"]["Count"] | components["schemas"]["Percent"] | components["schemas"]["Placeholder"] | components["schemas"]["Range"];
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "unverifiable" | "contradicted";
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "verified" | "scale_mismatch" | "wrong_value" | "wrong_metric" | "not_found" | "placeholder" | "section_not_found" | "extractors_disagree" | "not_in_document";
            /** Reason */
            reason: string;
            /** @default null */
            evidence: components["schemas"]["Evidence"] | null;
        };
        /** FinalEvent */
        FinalEvent: {
            /** Trace Id */
            trace_id: string;
            /** Score */
            score: number | null;
            /** N Numbers */
            n_numbers: number;
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * Code
             * @enum {string}
             */
            code: "llm_unavailable" | "models_warming_up" | "internal_error";
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_ipos_api_ipos_get: {
        parameters: {
            query?: {
                /** @description Company or sector search. */
                q?: string | null;
                sector?: string | null;
                year?: number | null;
                sort?: "listing_date" | "issue_size";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpoSummary"][];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_ipo_api_ipos__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpoDetail"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_xray_api_ipos__id__xray_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XRayResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_page_image_api_ipos__id__pages__n__get: {
        parameters: {
            query?: {
                /** @description Which document: the RHP or the final Prospectus. */
                doc?: "rhp" | "prospectus";
                /** @description Width in pixels (thumbnail) */
                w?: number | null;
            };
            header?: never;
            path: {
                id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_page_words_api_ipos__id__pages__n__words_get: {
        parameters: {
            query?: {
                /** @description Which document: the RHP or the final Prospectus. */
                doc?: "rhp" | "prospectus";
            };
            header?: never;
            path: {
                id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageWords"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    suggested_questions_api_ipos__id__suggested_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestedQuestion"][];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-sent events; see the x-sse-events map for each payload model. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    voice_api_voice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_voice_api_voice_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_trace_api_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lab_ladder_api_lab_ladder_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lab_fields_api_lab_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lab_verifier_api_lab_verifier_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lab_weaklabels_api_lab_weaklabels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lab_frontier_api_lab_frontier_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lab_retrieval_api_lab_retrieval_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lab_asr_api_lab_asr_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    glossary_api_glossary_get: {
        parameters: {
            query?: {
                lang?: "en" | "hi";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryEntry"][];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
